server:
  port: 9091
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/publisherconsumer
  username: root
  password: 12345
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa: 
  database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate.ddl-auto: update
 cloud:
  stream:
    bindings:
      input:
        destination: javanewstream
